react-navigation/stack

src/views/StackView/StackViewCard.js
src/views/StackView/StackViewLayout.js
src/views/StackView/screens.js

This PR introduces an abstraction for base components to be used as building blocks for navigation stack. We introduce `ScreenContainer` and `Screen` component. First representing a container in which `Screen`s can be rendered and is used in `StackViewLayout` where we render all the cards. Then `Screen` is used as a top level component for each `Card` and is directly rendered inside `ScreenContainer`.
On top of that each `Screen` component gets added `active` property which is interpolated such that the value is `1` when card is on top of the stack or second to last but we are transitioning, or `0` when there is no point for that card to be visible.
In the future this will allow for alternative native components to be used instead of Views that use platform specific abstraction to provide …

Use ScreenContainer and Screen components in stack - currently they fallback to RN's View

---

src/navigators/__tests__/__snapshots__/NestedNavigator-test.js.snap
src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap
src/views/Header/HeaderTitle.js

Moved this over from: https://github.com/react-navigation/react-navigation/pull/4807

Updated HeaderTitle fontWeight to match current iOS11&12 style

---

src/views/Header/Header.js
src/views/Header/HeaderStyleInterpolator.js

Bringing this over from https://github.com/react-navigation/react-navigation/pull/4787
Currently, headerBackground is sort of just plopped in place between scene changes which leads to it looking pretty jarring between transitions. What I'm proposing here is that we keep `headerBackground` rendered absolutely between scenes much like we do for the left, right and center. The default background interpolator transforms the x-axis moving it to the left and right as the scene transitions. This allows one to pull off the below in a much smoother fashion.

Animate headerBackground between scene transitions

---

src/views/StackView/StackViewCard.js

The react native `accessible` tag groups elements into a single selectable element for VoiceOver users. By setting the entire card `Screen` as `accessible={true}`, all interaction is disabled for VoiceOver users since the entire screen behaves as a single element.

Remove accessible tag from card

---

src/views/Header/HeaderBackButton.js
src/views/Header/HeaderTitle.js

The (potentially 3) nav elements including Title, Back/Left and Right buttons should be the ones that are accessible for interaction by VoiceOver users. All of their children elements should then not be accessible in order for proper VoiceOver use. Currently, because the children are accessible, the user gets stuck when they click just on the text or on one of the intermediate view components.

Remove accessible props from nav buttons children

---

src/views/StackView/StackViewCard.js

When poping a screen off the stack the indices change and the active interpolation no longer works properly. This causes a black screen for the screen under the screen that is being pop'ed. Not sure if there is a better way to adapt the interpolation but an easy fix is to make sure the active screen is never interpolates down to 0.
Tested in an app where I found the bug.

Fix black screen during the pop animation when using rn-screens

---

src/navigators/__tests__/__snapshots__/NestedNavigator-test.js.snap
src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap
src/views/StackView/StackViewLayout.js

The way floating header was implemented caused issues with rn-screens since it doesn't support touch events for view that overflow the `<ScreenContainer>`.
To avoid this we make sure `<ScreenContainer>` always cover the screen and use position absolute + some top padding when there is a header and no padding when there is no header.
Tested all 3 header modes in an app on screen with a header and no header.
Repro app: https://snack.expo.io/@kzzzf/blessed-bananas

Use padding instead of negative margin in StackViewLayout

---

src/views/StackView/StackView.js

StackView is responsible for calling the navigation completion action when `state.isTransitioning` is set. This fix handles that case when the stack is first mounting.
This had caused the following issue when observing the events.. because isTransitioning was never switched to false, didFocus never gets called: https://github.com/react-navigation/react-navigation/issues/4867

Stack nav completion on mount

---

src/views/StackView/StackViewLayout.js

The floating header is not displayed correctly on iPhone XS Max and iPhone XR due to the height being too small. It is displayed correctly however on iPhone X and XS thanks to the `IS_IPHONE_X` boolean being set to true.
Updated `IS_IPHONE_X` boolean to now be true for both iPhone XS Max and iPhone XR, in addition to the currently supported iPhone X and iPhone XS.
iPhone X and XS in portrait have a height dimension of `812`, while iPhone XS Max and iPhone XR  have a height dimension of `896`. This means apps using this library, will scale appropriately on both the iPhone XS Max and iPhone XR with this change.

Added window dimensions for iPhone XS Max and iPhone XR

---

src/views/Header/HeaderBackButton.js

We are using accessibility identifiers to click the buttons. It looks like we set accessibility label here... so setting `accessible` to `false` has probably been a mistake.

Make sure header back button is accessible

---

package.json

This allows all files to come with the npm package, and points Metro to the source code so that it can provide source maps for consumption in react-native apps.

Export all files from npm package

---

src/views/Transitioner.js

This call should be gated, same as the call on line 157. This wasn't noticed before because it's in a `!isTransitioning` special case. I noticed it because I'm using Redux integration in my store: it gets triggered when `redux-persist` rehydrates my Redux store, which triggers `Transitioner` without specifying `isTransitioning`.

Don't call onTransitionStart if unspecified

---

src/views/Header/HeaderBackButton.js

Hey! This is my pull request on this task:
https://github.com/react-navigation/react-navigation/issues/5028
I changed the accessibilityLabel prop value to:
```accessibilityLabel={title ? `${title}, back` : 'Go back'}``` so now if previous screen title is "Home" it reads as "Home, back, button"
I also spotted the situation when someone does not provide `title` in `navigationOptions`.
Previously it reads as "undefined, button" and now: "Go back, button"

change accessibilityLabel for HeaderBackButton - Fix iOS voiceover

---

example/src/SimpleStack.js
src/views/Transitioner.js

The problem with queued transitions currently is that *we compute the next scenes at the time of queuing* and *the current scenes are an input to that*, but the scenes change after the transition is completed and before the queued transition is fired! For example, when you pop a route the scene is still in the transitioner scenes state until once the transition is complete, so if you pop it and then before the transition is over you push a new route, then when the queued transition fires it will mount that scene again. That leads to issues like this: https://github.com/react-navigation/react-navigation/issues/5152
What I propose we do in this PR is that instead of computing scenes when props change before queueing the transition, we just store away the props at that point (that is, …

Rethink queued transitions

---

src/views/Header/Header.js

Within the `_renderLeftComponent` there is logic around wether or not the component should be rendered. This allows the `headerLeft: Component` to make these decisions within it's own rendering.
I don't believe there is any downside to passing these props through.
This is required because of the code introduced here: https://github.com/react-navigation/react-navigation/issues/4608 which alters the behaviour of `headerLeft` from v1 -> v2.

Allow headerLeft components to control their own rendering

---

src/views/StackView/StackViewLayout.js

Use the values provided by the user, not the values in the constants

gestureResponseDistance

---

src/views/StackView/StackViewStyleInterpolator.js

When animating new screen in on Android we used to, by default, fade out the previously displayed screen. Then when going back to it it would fade in from 0 to 1. This seem to be not how the default screen animation on Android performs and has also an additional consequence that the app background is partially visible during screen transition. It is because during transition both the transitioning in and transitioning out views are semi transparent.
Make Android default screen transition alike platform default one and also fix the problem when app background can be seen during transition.
This is potentially breaking change as it changes the default animation configuration on Android.
Note that there is another issue related to opacity not blending correctly when stack animation in …

Prevent previous screen fade out on push/pop on Android

---

src/views/Header/Header.js

Hello!
Header is positioned absolute in Layout layer already. Making container absolute prevents `StackViewLayout` to measure header height causing _jumpy header_ while switching screens.
The demo is available in #60
Thanks.

Fix transparent header height measurement (Fix #60)

---

src/views/Header/HeaderBackButton.js
src/views/Header/HeaderTitle.js

Fixed ["header titles not accessible #61" issue](https://github.com/react-navigation/react-navigation-stack/issues/61).
Fixed header back button accessibility for Android (TalkBack doesn't read button's role).

Header accessibility fixes

---

src/views/Transitioner.js

The idea was there, but the scope was wrong. Now, we actually wait for the onTransitionStart to complete its work before moving on instead of awaiting in a context with zero follow up procedures.
**Update:** I did actually test this against a working navigator. Render gets called, but no interpolation happens yet because the transition doesn't start. This is the intended and also documented behaviour.

fix: Transitioner await onTransitionStart

---

src/views/Header/Header.js
src/views/Header/HeaderBackButton.js

On iOS, apps can support larger font sizes for accessibility.
React-native supports this out-of-the-box, which is awesome. But the navigation bar turns into kind of a UX disaster:
Looking at default iOS apps provided by Apple, they often don't scale the navigation bar, which makes sense given the limited real-estate, so it's OK to turn that off. Like for example, here's what the settings app looks like with font-sizes maxed out.
And react-navigation provides an option for turning off font scaling for the title, getting us closer to a usable navigation bar:
```
navigationOptions: {
headerTitleAllowFontScaling: false,
}
```
But it doesn't have an option for the back button, which this PR addresses.
```
navigationOptions: {
headerBackAllowFontScaling: false, // new! …
```

iOS Accessibility - add headerBackAllowFontScaling option

---

src/index.js
src/navigators/createStackNavigator.js
src/views/Header/Header.js
src/views/Header/HeaderBackButton.js
src/views/Header/HeaderTitle.js
src/views/StackView/StackViewCard.js
src/views/StackView/StackViewLayout.js
src/views/StackView/StackViewTransitionConfigs.js

Fix how navigation works (by default) in preparation for Expo web.
* Make styles default to Material (same as RNWeb)
* Fixed minor bug where Assets returned nothing -- this throws in error in when users attempt to preload assets
* Fixed minor bug where null objects were being spread
* Prevent the use of `createKeyboardAwareNavigator` on web
#74 
[RNGH Web Support](https://github.com/kmagiera/react-native-gesture-handler/pull/406)

[Web] More web support

---

package.json
src/index.js
src/index.web.js
src/views/Header/HeaderTitle.js

This is the bare minimum needed to get stack navigator running in web. Seems like it will add some bloat to native though. If this is a concern, I can look at adding something like we did with ExpoLazy where a lazy loaded file is produced and used as the main path. Perhaps we could also just add it to the existing babel phase.
**Related react-navigation/react-navigation-core#45**
Related
* Should resolve styles by creating parity with existing native functionality: https://github.com/react-navigation/react-navigation/issues/4939
* No need to say this doesn't work on web after we make it work on web 😄  https://github.com/react-navigation/react-navigation-stack/issues/74

Remove commonJS on web

---

src/index.web.js
src/views/Header/BackButton.web.js
src/views/Header/Header.js
src/views/Header/HeaderBackButton.js
src/views/Header/HeaderTitle.js
src/views/StackView/StackViewLayout.js

* Using material SVG for back button due to safari image tint bug https://github.com/necolas/react-native-web/issues/1319
* Updated header bar height to be 64px
* Updated header title style to match material color, size, weight
* Changed how header margins work on web
* Removed assets on web

[web] Updated header style for web

---

src/views/StackView/StackView.js

When using a custom transitionConfig to describe transition animations, its `useNativeDriver` value is ignored by the stack view. This change ensures that the stack view will honour the value from the transitionConfig.
I just changed the order of the properties in `_configureTransition`, so it will return the default `USE_NATIVE_DRIVER` value if the user does not override it.

[iOS][Android] Prevent transitionConfig's useNativeDriver value being overwritten.

---

src/views/StackView/StackViewCard.js
src/views/StackView/StackViewLayout.js

In mobile Safari the header should collapse when content is scrolled. This will enable that functionality when header mode is set to `float`.
* Enabled body scrolling on web by preventing cards from clipping the scrollview.
* Relies on https://github.com/kmagiera/react-native-screens/pull/88/files

[web] Sticky Header

---

src/views/Transitioner.tsx

I don't feel confident trying to migrate this thing to `getDerivedStateFromProps` so...  `componentWillReceiveProps` -> `UNSAFE_componentWillReceiveProps`

Silence deprecated lifecycle warning in Transitioner

---

src/views/Stack/Card.tsx

This PR helps in two cases
1. The animation is not finished and the component is being unmounted. I manually invoke `onClose` method in this case.
2. Gesture breaks an animation's running. I manually invoke a proper listener in this case.

Make listeners more reliable

---

example/src/HeaderBackgrounds.js
example/src/HeaderPreset.js
example/src/ModalPresentation.js
example/src/WipeStack.js
src/types.tsx
src/views/Stack/Stack.tsx
src/views/Stack/StackItem.tsx
src/views/Stack/StackView.tsx

As @satya164 suggested in #154, instead of passing `navigationOptions` to interpolators, they can be allowed to specify their own interpolators.
Custom interpolator, if defined, takes precedence over the one from `NavigationConfig`. The rest of the logic stays the same.

feat: allow specifying separate style interpolators in navigationOptions

---

example/App.js
example/src/StackWithInput.js
package.json
src/navigators/__tests__/__snapshots__/NestedNavigator.test.tsx.snap
src/navigators/__tests__/__snapshots__/StackNavigator.test.tsx.snap
src/navigators/createStackNavigator.tsx
src/views/KeyboardManager.tsx
src/views/Stack/Stack.tsx
src/views/Stack/StackItem.tsx
src/views/Stack/StackView.tsx

The HOC currently forces us to expose some options in stack config which we don't want to. So we vendor this functionality for now to avoid this.

refactor: don't use keyboardAwareNavigator

---

src/views/Stack/Card.tsx

Double multiplication of gesture velocity was making the card too sensitive—reduced to 1x multiplication and increased `SWIPE_VELOCITY_IMPACT` to compensate.

Reduce card gesture velocity impact

---

src/types.tsx
src/views/Stack/Stack.tsx
src/views/Stack/StackItem.tsx

I've added a param to the user facing `onTransitionStart/End` callback informing whether screen transition was opening or closing the screen.
There are use cases where being able to have such information is crucial, since because of ability to 'put screen back instead of discarding it completely', it is impossible to rely on boolean logic for knowing whether if screen is opening or closing.
And to give a little bit more context, my exact case where I needed it was setting `StatusBar` in `onTransitionStart` so it fits screen's animation better.

feat: inform whether screen is opening/closing in onTransition callbacks

---

src/types.tsx
src/views/Stack/Stack.tsx

As suggested by @satya164, I am submitting another PR changing single argument `closing` to an extendable properties object.

feat: change single param to props object in onTransition callbacks

---

src/types.tsx
src/views/Header/HeaderSegment.tsx

* adds `headerLeftTintColor` and `headerRightTintColor` options
Fixes https://github.com/react-navigation/stack/issues/197

feat: support multiple tint colors for `HeaderSegment`

---

example/App.js
example/src/DragLimitedToModal.js
src/navigators/__tests__/__snapshots__/NestedNavigator.test.tsx.snap
src/navigators/__tests__/__snapshots__/StackNavigator.test.tsx.snap
src/views/Stack/Card.tsx

I was trying to achieve the following effect:
The transition used to dismiss modal by dragging it down, should only respond to gesture on the modal itself, not any background.
I found out that I can achieve it by using the way stack hierarchy works:
The screen component is wrapped by 'card' component which is wrapped in a pan gesture handler which is then wrapped in 'container' component.
If I specified `height` and `width` for the card component, it worked perfectly. However, there was still a problem with dynamically sized modals, since `flex: 1` is present in container, card and another internal component wrapping the screen which is called `<PointerEventsView>`.
The least invasive way to solve it which allows for dynamically sized modals and doesn't require API changes would be to …

feat: if cardStyle has flexed specified, set the same value on PointerEventsView

---

src/utils/validateDeprecatedOptions.tsx

`headerTitle` deprecation warning was evaluating prop type of `header`.  This PR fixes that.

fix: Fixed headerTitle deprecation warning

---

.circleci/config.yml

The checksum should be always from the lockfile, not the package.json file.
Also see https://github.com/circleci/circleci-docs/issues/3772

ci: use lockfile checksum for cache key computation

---

src/views/KeyboardManager.tsx

When user has super short swiping interaction it's an issue that keyboard won't reappear on screen. 
That's because there is short time when system will make sure to hide keyboard no matter what. Too fast text input refocus will result only in keyboard flashing on screen and hiding right away.
For such short interactions I created a delay that will ensure that the keyboard will reappear on the screen every time and make sure it's executed only when needed.
It only affect super short interactions <100ms to make sure they work correctly, and doesn't affect any logic beyond that. 
As far as my research go it seems that the react-navigation isn't responsible for hiding the Keyboard in that specific case, so I don't think we can simply prevent this action when we don't want it. Doing the check …

fix: handle keyboard return for short interactions

---

example/App.tsx
example/src/StackAnimationConsumerStack.tsx
src/index.tsx
src/utils/StackAnimationIsClosingContext.tsx
src/utils/StackAnimationIsSwipingContext.tsx
src/utils/StackAnimationProgressContext.tsx
src/views/Stack/Card.tsx
src/views/Stack/Stack.tsx

This PR exposes transition's progress and when user is swiping via context. Both `Animated.Value`'s are passed as value into two new contexts (i.e. `StackAnimationProgressContext` and `StackAnimationIsSwipingContext`). This allows consumers to define custom transitions/animations based on those values. A new example was added in `examples` directory.
<details>
<summary>GIF of example</summary>
</details>
Closes https://github.com/react-navigation/stack/issues/183

feat: expose stack transition values via context

---

example/src/StackAnimationConsumerStack.tsx
src/index.tsx
src/utils/StackAnimationIsClosingContext.tsx
src/utils/StackAnimationIsSwipingContext.tsx
src/utils/StackAnimationProgressContext.tsx
src/utils/StackCardAnimationContext.tsx
src/views/Stack/Card.tsx

This pull request addresses an important shortcoming of the previous PR #183 where the wrong progress value was provided for the first of two screens in a transition. 
@satya164, @samchamberland

feat: expose animation related properties in context

---

src/views/Header/HeaderContainer.tsx

Issue reproduction:
1. Add a custom touchable element to either headerLeft or right.
2. Push a new screen
3. You are still able to press the underlying element even if it's not visible.

fix: children touch events leaking to underlying Header right/left components

---

package.json

Since using `react-navigation-stack` with `react-native-screens ^2.0.0-alpha` does not represent an issue, it just causes an annoying warning when linking dependencies.

fix: add ^2.0.0-alpha to react-native-screens peer dependency
